### ISSUE TITLE
Could not pass the C\RTL Cosimulation in Vitis 2021.2

### ISSUE THREAD

**Issue by NvCenters** [Nunigan/MNIST_HLS#1]
Hi! I tried to reproduce this accelerated core, but it failed. It reported in C\RTL Cosimulation  :

`ERROR: System recieved a signal named SIGSEGV and the program has to stop immediately!
This signal was generated when a program tries to read or write outside the memory that is allocated for it, or to write memory that can only be read.
Possible cause of this problem may be: 1) the depth setting of pointer type argument is much larger than it needed; 2)insufficient depth of array argument; 3)null pointer etc.
Current execution stopped during CodeState = DELETE_CHAR_BUFFERS.
You can search CodeState variable name in apatb*.cpp file under ./sim/wrapc dir to locate the position.
`

**Comment by Nunigan** [comment]
The used [hlslib](https://github.com/definelicht/hlslib) does not support CoSim.
